CREATE DATABASE University 

USE University

CREATE TABLE Majors 
(
	MajorID INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(50) NOT NULL,
)

CREATE TABLE Students 
(
	StudentID INT PRIMARY KEY IDENTITY,
	StudentNumber CHAR(8) NOT NULL,
	StudentName VARCHAR(20) NOT NULL,
	MajorID INT FOREIGN KEY REFERENCES  Majors(MajorID) NOT NULL,
)

CREATE TABLE Payments 
(
	PaymentsID INT PRIMARY KEY IDENTITY,
	PaymentDate DATE NOT NULL,
	PaymentAmount DECIMAL(6,2) NOT NULL,
	StudentID INT FOREIGN KEY REFERENCES  Students(StudentID) NOT NULL,
)

CREATE TABLE Subjects 
(
	SubjectID INT PRIMARY KEY IDENTITY,
	SubjectName VARCHAR(50) NOT NULL,
)

CREATE TABLE Agenda 
(
	StudentID INT FOREIGN KEY REFERENCES Students(StudentID) NOT NULL,
	SubjectID INT FOREIGN KEY REFERENCES Subjects(SubjectID) NOT NULL,
	PRIMARY KEY(StudentID, SubjectID)
)
